### ISSUE TITLE
Error Executing Globio 4 - Files not found

### ISSUE THREAD

**Issue by olgauss** [GLOBIO4/GlobioModelPublic#4]
Hi, 
I am trying to run globio4 as described in the wiki, however, when using the -doc option it shows it does not find any of the Scripts defined in the Globio_Modules.glo and Globio_Utilities.glo files. I attach a screenshot of what I get. 

Do I need to change something in the Globio_Config.glo file? 

Thanks in advance for your help!
 
![image](https://github.com/GLOBIO4/GlobioModelPublic/assets/45953702/822eb32e-3010-4207-9ae3-1a4a3d60e57a)

**Comment by martijnvandermarel** [comment]
Hi, thanks for creating this issue! Could you share the contents of your `globio4.bat` file, and if applicable any other possible changes you might have made to the model? If you prefer, we can also help you via email (email address can be found on our website)

**Comment by HansWes** [comment]
Hi, 
Did you find a solution to this issue? I'm running into the same problem.
Currently I have this in my `globio4.bat` file:

```batch
@REM ### Activate globio environment.
call C:\Anaconda3\condabin\conda activate globio41

@REM ### Set GLOBIO4 env. var.
set GLOBIO4=C:\<user>\Documents\GitHub

@REM ### Set PYTHON env. vars.
set PYTHONEXEPATH=C:\Anaconda3\envs\globio41
set PYTHONEXE=%PYTHONEXEPATH%\python.exe

@REM ### Set GRASS env. vars.
set GRASS=C:\Program Files\GRASS GIS 8.3\grass83
set GISBASE=%GRASS%

@REM ### Set TauDEM path.
set TAUDEMPATH=%PYTHONEXEPATH%\Library\bin\

@REM ### Set PYTHONPATH env. var.
set PYTHONPATH=%GLOBIO4%;%GRASS%\etc\python

@REM ### Run globio Python script.
%PYTHONEXE% "%GLOBIO4%\GlobioModel\Core\Globio4.py" %1 %2
```

**Comment by martijnvandermarel** [comment]
Thanks for the reply. I have trouble replicating the exact issue, but I do know the following can cause `file not found` errors:
* spaces in paths
* invalid `GRASS` path

For me, the `GRASS` variable does not have the `grass83` path component at the end, so you could try removing that. I use GRASS 8.2, which might also cause the difference.

The following may fix the above issues:
* wrapping variable definitions in quotes: `set "GLOBIO4=C:\<user>\Documents\GitHub"`
* removing the `GRASS` and `GISBASE` variable definitions (only if you don't need the GLOBIO modules that use GRASS)

Please let me know if any of the above fixes your issues.

**Comment by guojingpeng1122** [comment]
Hi,
Did you find a solution to this issue? I'm running into the same problem.

(globio41) C:\Users\DELL\Downloads\Compressed\GlobioModelPublic-main>globio4 -doc
================================================================================
# GLOBIO 4.1, feb 2021                                           (Framework 1.1)
================================================================================
Loading file C:\Users\DELL\Downloads\Compressed\GlobioModelPublic-main\GlobioModel\Config\Globio_Modules.glo
Error: GLOBIO calculation file 'GLOBIO_CalcNaturalLanduse.py' not found. - Globio_Modules.glo:34
Error: GLOBIO calculation file 'GLOBIO_CalcDominantLanduse.py' not found. - Globio_Modules.glo:42
Error: GLOBIO calculation file 'GLOBIO_CalcSettlements.py' not found. - Globio_Modules.glo:50
Error: GLOBIO calculation file 'GLOBIO_CalcLanduseMSA.py' not found. - Globio_Modules.glo:59
Error: GLOBIO calculation file 'GLOBIO_CalcLanduseMSARestoration.py' not found. - Globio_Modules.glo:73
Error: GLOBIO calculation file 'GLOBIO_CalcLanduseBiomesMSA.py' not found. - Globio_Modules.glo:85
Error: GLOBIO calculation file 'GLOBIO_CalcClimateChangeMSA.py' not found. - Globio_Modules.glo:96
Error: GLOBIO calculation file 'GLOBIO_CalcNDepositionMSA.py' not found. - Globio_Modules.glo:111
Error: GLOBIO calculation file 'GLOBIO_CalcSettlementDistance.py' not found. - Globio_Modules.glo:127
Error: GLOBIO calculation file 'GLOBIO_CalcHumanEncroachmentMSA_V2b.py' not found. - Globio_Modules.glo:164
Error: GLOBIO calculation file 'GLOBIO_CalcInfraDisturbanceMSA.py' not found. - Globio_Modules.glo:185
Error: GLOBIO calculation file 'GLOBIO_CalcInfraFragmentationMSA.py' not found. - Globio_Modules.glo:200
Error: GLOBIO calculation file 'GLOBIO_CalcTerrestrialMSA.py' not found. - Globio_Modules.glo:221
Error: GLOBIO calculation file 'GLOBIO_CalcOverallTerrestrialMSA.py' not found. - Globio_Modules.glo:234
Error: GLOBIO calculation file 'GLOBIO_CalcSplitImpactsMSA.py' not found. - Globio_Modules.glo:258
Error: GLOBIO calculation file 'GLOBIO_CalcMSAregion_V2.py' not found. - Globio_Modules.glo:290
Error: GLOBIO calculation file 'GLOBIO_CalcMSAregion_V2_percentile.py' not found. - Globio_Modules.glo:316
Error: GLOBIO calculation file 'GLOBIO_Histogram.py' not found. - Globio_Modules.glo:333
Loading file C:\Users\DELL\Downloads\Compressed\GlobioModelPublic-main\GlobioModel\Config\Globio_Utilities.glo
Error: GLOBIO calculation file 'GLOBIO_CompareRasters.py' not found. - Globio_Utilities.glo:28
Error: GLOBIO calculation file 'GLOBIO_CompareShapeFiles.py' not found. - Globio_Utilities.glo:40
Errors found in the GLOBIO configuration. Stopped.
================================================================================

Currently I have this in my file:globio4.bat

@REM ### Activate globio environment.
call C:\ProgramData\anaconda3\condabin\conda.bat activate globio41

@REM ### Set GLOBIO4 env. var.
set GLOBIO4=C:\Users\DELL\Downloads\Compressed\GlobioModelPublic-main

@REM ### Set PYTHON env. vars.
set PYTHONEXEPATH=C:\Users\DELL\.conda\envs\globio41
set PYTHONEXE=%PYTHONEXEPATH%\python.exe

@REM ### Set GRASS env. vars.
set GRASS=C:\Program Files\GRASS GIS 8.2
set GISBASE=%GRASS%

@REM ### Set TauDEM path.
set TAUDEMPATH=%PYTHONEXEPATH%\Library\bin\

@REM ### Set PYTHONPATH env. var.
set PYTHONPATH=%GLOBIO4%;%GRASS%\etc\python

@REM ### Run globio Python script.
%PYTHONEXE% %GLOBIO4%\GlobioModel\Core\Globio4.py %1 %2

**Comment by HansWes** [comment]
Hi @martijnvandermarel,

Thanks for getting back to me.
I tried wrapping the definitions in quotes and tried removing the grass path entirely, but still it gives the same errors.

It could also be that the input files are missing, but hard to discover which ones since the error only mentions the calculation files can't be found. 
And the input files mentioned in the Wiki here: https://github.com/GLOBIO4/GlobioModelPublic/wiki/Land-Use-Allocation-module, are tough to find, since versions of these files have changed. It is also mentioned some have to be pre-processed.

So all in all for now I will have to give up trying to get this to work.

**Comment by martijnvandermarel** [comment]
@HansWes I'm sorry to hear that. We are working on improving the model and how to run it and these updates will also be pushed to the public repository, so perhaps check back.

I recognize that this problem is relatively common, however I can't reproduce it. What I can do is share my own local `globio4.bat`, which may be helpful for some.

```
@REM ### Activate globio environment.
call C:\Users\USER\AppData\Local\anaconda3\condabin\conda activate globio41

@REM ### Set GLOBIO4 env. var.
set "GLOBIO4=C:\Users\USER\path to\public_model_workspace"

@REM ### Set PYTHON env. vars.
set PYTHONEXEPATH=C:\Users\USER\AppData\Local\anaconda3\envs\globio41
set PYTHONEXE=%PYTHONEXEPATH%\python.exe

@REM ### Set GRASS env. vars.
set GRASS=C:\Users\USER\AppData\Local\GRASS_GIS_8.2
set GISBASE=%GRASS%

@REM ### Set TauDEM path.
set TAUDEMPATH=%PYTHONEXEPATH%\Library\bin\

@REM ### Set PYTHONPATH env. var.
set PYTHONPATH=%GLOBIO4%;%GRASS%\etc\python

@REM ### Run globio Python script.
%PYTHONEXE% "%GLOBIO4%\GlobioModel\Core\Globio4.py" %1 %2
```

**Comment by olgauss** [comment]
Sorry for the late reply. In my case the issue was solved when changing the GRASS and GISBASE paths separately as:

@REM ### Set GRASS env. vars.
set GRASS=C:\Program Files\GRASS GIS 8.3\gras83
set GISBASE=C:\Program Files\GRASS GIS 8.3

Hope it helps the others too.

**Comment by guojingpeng1122** [comment]
@olgauss  Unfortunately, my problem persists! I would like to see your
C:\Program Files\GRASS GIS 8.3\gras83 vs.
C:\Program Files\GRASS GIS 8.3 directory file difference

**Comment by olgauss** [comment]
> @olgauss Unfortunately, my problem persists! I would like to see your C:\Program Files\GRASS GIS 8.3\gras83 vs. C:\Program Files\GRASS GIS 8.3 directory file difference

![image](https://github.com/GLOBIO4/GlobioModelPublic/assets/45953702/d304195a-5104-4453-9efb-14b3c43e221f)

**Comment by guojingpeng1122** [comment]
I'm sorry I'll bother you again.
In your directory, C:\Program Files\GRASS GIS 8.3\gras83 directory does not seem to exist. 
C:\Program Files\GRASS GIS 8.3\gras83 is meant to express C:\Program Files\GRASS GIS 8.3\grass83.bat? 
I tried setting GRASS=C:\Program Files\GRASS GIS 8.3\grass83.bat, but the problem is still not solved!

**Comment by guojingpeng1122** [comment]
@olgauss I'm sorry I'll bother you again.
In your directory, C:\Program Files\GRASS GIS 8.3\gras83 directory does not seem to exist.
C:\Program Files\GRASS GIS 8.3\gras83 is meant to express C:\Program Files\GRASS GIS 8.3\grass83.bat?
I tried setting GRASS=C:\Program Files\GRASS GIS 8.3\grass83.bat, but the problem is still not solved!
